Disable Scaladoc generation in ensime.
It fails with:
[ensime] [info] Compiling 73 Scala sources to .../target/scala-2.11/classes...
[ensime] [info] Main Scala API documentation to .../target/scala-2.11/api...
[ensime] [error] .../src/main/scala/org/ensime/indexer/SourceResolver.scala:55: value toMultiMap is not a member of scala.collection.immutable.Set[(org.ensime.indexer.PackageName, org.apache.commons.vfs2.FileObject)]
[ensime] [error] possible cause: maybe a semicolon is missing before `value toMultiMap'?
[ensime] [error]   }.toMultiMap[Set]

I don't know the reason.