2.13: remove ssl-config from expected-failure list
because whatever this is:

    scala.MatchError: FastTypeTag[sbt.CrossVersion]
      (of class scala.pickling.FastTypeTag$$anon$2)

I'm not able to reproduce it on my Mac, and it didn't start happening
until recently, and it's maybe some dbuild or sbt bug, anyway, not an
"expected" failure

nyaya is affected as well, but I'm leaving it on the expected
list for now because iirc it would still fail for some other reason